# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHistoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name_plural': 'Songs'},
        ),
    ]
