# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHistoryAPI', '0003_auto_20170201_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_release_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_release_date',
        ),
    ]
