# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHistoryAPI', '0005_auto_20170201_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=128),
        ),
    ]
