# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicHistoryAPI', '0006_auto_20170201_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='SOME STRING', max_length=128),
        ),
    ]
